# Generated by Django 6.0.3 on 2026-03-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='course_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='course_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
