# Generated by Django 6.0.3 on 2026-04-03 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_testimonial_course_name_testimonial_course_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='course_url',
        ),
    ]
