# Generated by Django 6.0 on 2026-03-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='category',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=4),
        ),
    ]
