# Generated by Django 5.2.8 on 2026-03-25 09:43

from django.db import migrations, models


def update_existing_categories(apps, schema_editor):
    Category = apps.get_model('category', 'Category')
    
    # Update all existing categories to 9% except Apparel
    Category.objects.filter(category_name__iexact='apparel').update(cgst=2.50, sgst=2.50)
    Category.objects.exclude(category_name__iexact='apparel').update(cgst=9.00, sgst=9.00)


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_cgst_category_sgst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='category',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=4),
        ),
        migrations.RunPython(update_existing_categories),
    ]
