# Generated by Django 6.0.4 on 2026-05-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_payment_total_price'),
    ]

    operations = [
    ]
