# Generated by Django 5.2.8 on 2026-03-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_id_alter_orderproduct_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='cgst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='sgst',
            field=models.FloatField(default=0),
        ),
    ]
